### ISSUE TITLE
Application of data.gov.cz style, flags, project publicity

### ISSUE THREAD

**Issue by jakubklimek** [opendata-mvcr/termit#10]
The assembly line is approaching the phase where it will be shown to the public. It is necessary to harmonize it visually with the rest of the data.gov.cz
- [ ] colors - see data.gov.cz, consider dark mode support
- [ ] flag - see data.gov.cz
- [ ] project publicity - see data.gov.cz

**Comment by ledsoft** [comment]
Not relevant for backend. Replicated the issue in frontend: https://github.com/opendata-mvcr/termit-ui/issues/15

**Comment by jakubklimek** [comment]
@ledsoft Understood. The issue could also be transferred instead of replicating.
