### ISSUE TITLE
Contextualize dashboard content based on workspace

### ISSUE THREAD

**Issue by ledsoft** [opendata-mvcr/termit#21]
Dashboard widgets displaying recently edited assets and my assets currently do not take workspaces into account. This leads to issues when the user clicks on a term which is not in their workspace and an error is shown. Therefore, these widgets should only display data from the current workspace.

Consider also statistics - maybe they should also be based on the current workspace.

**Comment by ledsoft** [comment]
@psiotwo What do you think about the statistics? Should they be based on workspace or not? Thanks

**Comment by psiotwo** [comment]
Ah sure - I think that the current version of TermIt KODI should be fully workspace-specific. (Cf. using TermIt as a public SGoV-wide browser using only R/O view. Let's discuss this bit on replenishment.)

So yes, https://github.com/opendata-mvcr/termit/issues/24
