### ISSUE TITLE
Term detail fails to open

### ISSUE THREAD

**Issue by psiotwo** [opendata-mvcr/termit#24]
After successful opening of a workspace from control panel, I am able to see vocabulary detail and term list for the given vocabulary

![image](https://user-images.githubusercontent.com/1140626/87200386-b60bdf80-c2fc-11ea-81bf-315c66d0a853.png)

Clicking on any term to show its detail fails, however. Blank screen appears, leaving an error in console 
![image](https://user-images.githubusercontent.com/1140626/87200572-2286de80-c2fd-11ea-8530-3ed06786b51f.png)

pointing to
https://reactjs.org/docs/error-decoder.html/?invariant=31&args[]=object%20with%20keys%20%7Biri%7D&args[]=

**Comment by ledsoft** [comment]
It would be nice to know which and in which workspace.

**Comment by ledsoft** [comment]
Fixed (problem in the UI). Feel free to re-open if the problem resurfaces.
