### ISSUE TITLE
Upon opening a workspace with two vocabularies only one is shown

### ISSUE THREAD

**Issue by psiotwo** [opendata-mvcr/termit#25]
Workspace https://slovn%C3%ADk.gov.cz/datov%C3%BD/pracovn%C3%AD-prostor/pojem/metadatov%C3%BD-kontext/instance754162693 contains two vocabulary contexts (

d-sgov-pracovní-prostor-pojem:slovníkový-kontext/instance-780386936
d-sgov-pracovní-prostor-pojem:slovníkový-kontext/instance-872997630

one with V-SGoV (read only) the other with G-SGoV-turistické cíle.

However, opening TermIt using

https://kbss.felk.cvut.cz/termit-kodi/#/?workspace=https://slovn%C3%ADk.gov.cz/datov%C3%BD/pracovn%C3%AD-prostor/pojem/metadatov%C3%BD-kontext/instance754162693

shows just one vocabulary in the list (G-SGoV-turistické-cíle)

**Comment by ledsoft** [comment]
I don't see any data in the context `d-sgov-pracovní-prostor-pojem:slovníkový-kontext/instance-872997630`.
