### ISSUE TITLE
The term tree does not show parents from the same workspace

### ISSUE THREAD

**Issue by psiotwo** [opendata-mvcr/termit#69]
I have two vocabularies in a workspace. In one of them I create a term A and specify  its parent (say B)  from the other vocabulary. But the term tree does not show B (only A as a top-level element).

**Comment by ledsoft** [comment]
Works as intended.

Since this version does not support explicit vocabulary imports (on which the toggable display of imported (parent) terms was based), the Term tree always shows only terms from the current vocabulary.
